// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

namespace Models.Configuration
{
    using System;
    using System.Text.Json.Serialization;

    public class DiscordConfig
    {
        [JsonPropertyName("application")]
        public Application Application { get; set; }

        [JsonPropertyName("bot")]
        public Bot Bot { get; set; }
    }

    public class Application
    {
        [JsonPropertyName("appId")]
        public string AppId { get; set; }

        [JsonPropertyName("publicKey")]
        public string PublicKey { get; set; }
    }

    public class Bot
    {
        [JsonPropertyName("token")]
        public string Token { get; set; }

        [JsonPropertyName("clientId")]
        public string ClientId { get; set; }

        [JsonPropertyName("clientSecret")]
        public string ClientSecret { get; set; }

        [JsonPropertyName("url")]
        public Uri Url { get; set; }
    }
}
