// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

namespace Models.Configuration
{
    using System;
    using System.Text.Json.Serialization;

    public class DiscordConfig
    {
        [JsonPropertyName("Application")]
        public Application Application { get; set; }

        [JsonPropertyName("Bot")]
        public Bot Bot { get; set; }
    }

    public class Application
    {
        [JsonPropertyName("AppId")]
        public string AppId { get; set; }

        [JsonPropertyName("PublicKey")]
        public string PublicKey { get; set; }
    }

    public class Bot
    {
        [JsonPropertyName("Token")]
        public string Token { get; set; }

        [JsonPropertyName("ClientId")]
        public string ClientId { get; set; }

        [JsonPropertyName("ClientSecret")]
        public string ClientSecret { get; set; }

        [JsonPropertyName("Url")]
        public Uri Url { get; set; }
    }
}
